title: just-doodle
description: "just doodle by just ysc"
author:
  name: "just-ysc"
  email: "cks6589@snu.ac.kr"
  url: "https://github.com/just-ysc"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 5
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "just-ysc"
year : "2024"
